name: Deploy .NET Backend to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'SentimentAnalysis.API/**'
      - 'SentimentAnalysis.Domain/**'
      - 'SentimentAnalysis.Infrastructure.Data/**'
      - '.github/workflows/azure-backend-deployment.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'SentimentAnalysis.API/**'
      - 'SentimentAnalysis.Domain/**'
      - 'SentimentAnalysis.Infrastructure.Data/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: sentiment-analysis-api-1
  AZURE_WEBAPP_PACKAGE_PATH: './SentimentAnalysis.API'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
      continue-on-error: true
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/TestResults/**/*.xml'

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build and publish
      run: |
        dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/SentimentAnalysis.API.csproj \
          --configuration Release \
          --output ./publish \
          --self-contained false \
          --runtime linux-x64
          
    - name: Create deployment package
      run: |
        cd ./publish
        zip -r ../deployment.zip .
        
    - name: Upload deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package-production
        path: deployment.zip
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure App Service (Production)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: deployment.zip
        
    - name: Health check (Production)
      run: |
        sleep 30
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health || echo "Health check failed but continuing..."
        
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Production deployment successful!"
        echo "🌐 Application URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Production deployment failed!"
        echo "Please check the logs and investigate the issue."